spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bbdcoffee
    username: root
    password: S@nketh8

  #Jpa Settings
  jpa:
    hibernate.ddl_auto: update
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
